### ISSUE TITLE
Multiple Streams using AioQuic

### ISSUE THREAD

**Issue by devkdas** [MaxF12/draft-jholland-quic-multicast#2]
hai ,

It is not an issue.
one small quick query

@MaxF12 
Could you please confirm were you able to create multiple streams in a single connection using the AIOQUIC code you have in Github.

Sorry for raising an issue as i am unable to find your email to ask this query.

Looking forward for your reply

Thank you.

**Comment by Karthikdasari0423** [comment]
Hai @MaxF12 

Thank you for replying back.

Okay,i have tried on  "Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-113-generic x86_64)" **_terminal_** ,"Python 3.8.10" . but unable to see a multiple streams on any of  quic log files.

Thank you,
@Karthikdasari0423
